preload = /home/holy_arch/Pictures/wallpapers/hello-kitty-amoled-5120x2880-25116.png
wallpaper = /home/holy_arch/Pictures/wallpapers/hello-kitty-amoled-5120x2880-25116.png


# Выключаем сплэш-надписи снизу
splash = false
