general {
    lock_cmd = pidof hyprlock || hyprlock       # Команда для блокировки
    before_sleep_cmd = loginctl lock-session    # Блокировать перед сном
    after_sleep_cmd = hyprctl dispatch dpms on  # Включать экран при пробуждении
}

# Тушить подсветку клавиатуры через 2.5 минуты простоя
listener { 
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Блокировать экран через 5 минут
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Выключать дисплей через 5.5 минут (экономия OLED)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Уводить ноут в сон через 15 минут
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
