# Предзагрузка изображения (полный путь!)
preload = /home/holy_arch/Pictures/wallpapers/hacker-hacking-3840x2160-15637.jpeg

# Установка на монитор (eDP-1 — это обычно встроенный экран ноутбука)
wallpaper = eDP-1,/home/holy_arch/Pictures/wallpapers/hacker-hacking-3840x2160-15637.jpeg

# Выключаем сплэш-надписи снизу
splash = false
