font_family      Hack Nerd Font
font_size        14.0
cursor_shape     block
cursor_blink_interval 0

# Pure Black OLED
foreground       #ffffff
background       #000000
selection_foreground #000000
selection_background #ffffff

# Border
window_padding_width 10
confirm_os_window_close 0

# Цвета (Monochrome/Minimal)
color0 #000000
color8 #444444
color7 #bbbbbb
color15 #ffffff
